include: package:very_good_analysis/analysis_options.9.0.0.yaml
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/*.iconfig.dart"
    - "**/*.p.dart"
    - "**/*.r.dart"
    - "**/*.router.dart"
    - "**/*.theme.dart"
    - "**/*.w.dart"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/*.iconfig.dart"
    - "**/*.p.dart"
    - "**/*.r.dart"
    - "**/*.router.dart"
    - "**/*.theme.dart"
    - "**/*.w.dart"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/*.iconfig.dart"
    - "**/*.p.dart"
    - "**/*.r.dart"
    - "**/*.router.dart"
    - "**/*.theme.dart"
    - "**/*.w.dart"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/*.iconfig.dart"
    - "**/*.p.dart"
    - "**/*.r.dart"
    - "**/*.router.dart"
    - "**/*.theme.dart"
    - "**/*.w.dart"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/*.iconfig.dart"
    - "**/*.p.dart"
    - "**/*.r.dart"
    - "**/*.router.dart"
    - "**/*.theme.dart"
    - "**/*.w.dart"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/*.iconfig.dart"
    - "**/*.p.dart"
    - "**/*.r.dart"
    - "**/*.router.dart"
    - "**/*.theme.dart"
    - "**/*.w.dart"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/*.iconfig.dart"
    - "**/*.p.dart"
    - "**/*.r.dart"
    - "**/*.router.dart"
    - "**/*.theme.dart"
    - "**/*.w.dart"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/*.iconfig.dart"
    - "**/*.p.dart"

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    sort_constructors_first: false
    library_private_types_in_public_api: false