name: date_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  dio: ^5.9.0
  flutter_native_splash: ^2.4.6
  icons_launcher: ^3.0.1
  get_it: ^8.2.0
  easy_localization: ^3.0.8
  injectable: ^2.5.1
  auto_route: ^10.1.2
  json_annotation: ^4.9.0
  logger: ^2.6.1
  lottie: ^3.3.1
  shared_preferences: ^2.5.3
  infinite_scroll_pagination: ^5.1.0
  envied: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.8.1
  build_runner: ^2.7.0
  auto_route_generator: ^10.2.4
  flutter_lints: ^6.0.0
  json_serializable: ^6.10.0
  very_good_analysis: ^9.0.0
  envied_generator: ^1.2.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lang/en.json
    - assets/lang/tr.json

