// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ93tFKqUDty0eAY1Dvidf3r1cGAsTHjo',
    appId: '1:1078825467497:web:1b6156ccf03b4f07526cf8',
    messagingSenderId: '1078825467497',
    projectId: 'reelix-e6a5c',
    authDomain: 'reelix-e6a5c.firebaseapp.com',
    storageBucket: 'reelix-e6a5c.firebasestorage.app',
    measurementId: 'G-L8ES9DGG8C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC10zOzDU8FEun4-VBBoAXpHad2jvr3C7Q',
    appId: '1:1078825467497:android:644232f91b79f322526cf8',
    messagingSenderId: '1078825467497',
    projectId: 'reelix-e6a5c',
    storageBucket: 'reelix-e6a5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCch94Ssdpjmlg2JO9DHdQzAjsWoD6YnOk',
    appId: '1:1078825467497:ios:1bcc17969f932a02526cf8',
    messagingSenderId: '1078825467497',
    projectId: 'reelix-e6a5c',
    storageBucket: 'reelix-e6a5c.firebasestorage.app',
    iosBundleId: 'com.example.reelix',
  );
}
